### ISSUE TITLE
Use of SOCK_NONBLOCK is not supported on some operating systems

### ISSUE THREAD

**Issue by wahjava** [OpenSMTPD/OpenSMTPD#702]
On FreeBSD 9.x at least, and maybe NetBSD 7 too (as per `socketpair(2)`), latest snapshot fails with following compiler error:

```
../../smtpd/smtpd.c: In function 'start_child':
../../smtpd/smtpd.c:846: error: 'SOCK_NONBLOCK' undeclared (first use in this function)
../../smtpd/smtpd.c:846: error: (Each undeclared identifier is reported only once
../../smtpd/smtpd.c:846: error: for each function it appears in.)
../../smtpd/smtpd.c: In function 'setup_peers':
../../smtpd/smtpd.c:887: error: 'SOCK_NONBLOCK' undeclared (first use in this function)
```

It seems to be introduced in b5ccee5fb. Could you please provide a workaround for OSes where it's not available ?

Thanks!

**Comment by poolpOrg** [comment]
Hi,

I have just committed a fix to git, care to give it a try and confirm it fixes your build before I publish a new snapshot ?

https://github.com/OpenSMTPD/OpenSMTPD/commit/1d0a360672c9a61495605fc2adec9aec063d1a6e#diff-d130386f59ceeb128858fa6252db80a4

**Comment by wahjava** [comment]
Thanks for the fix. It builds fine now.
